data:
  format: h5
  name: aliexpress
  num_features: 75
  path: /aliexpress/
  short_name: ali
  task_out_dim:
    click: 1
    conversion: 1
  task_type:
    click: binary
    conversion: binary
  tasks:
  - click
  - conversion